package templates

import (
	"embed"
	"fmt"
	"text/template"
)

//go:embed *.tmpl
var templatesFS embed.FS

// Templates holds all parsed templates
var Templates *template.Template

func init() {
	var err error
	Templates, err = template.ParseFS(templatesFS, "*.tmpl")
	if err != nil {
		panic(fmt.Sprintf("failed to parse templates: %v", err))
	}
}

// Data holds template context data
type Data struct {
	ProjectName string
	ModuleName  string
	GoVersion   string
	ForgeRoot   string
}

// GoHeader returns the standard generated file header for Go files
func GoHeader(name string) string {
	return fmt.Sprintf("// Code generated by pdfforge-cli init for project %q.\n// pdf-forge: https://github.com/rendis/pdf-forge\n\n", name)
}

// ShHeader returns the standard generated file header for shell/yaml files
func ShHeader(name string) string {
	return fmt.Sprintf("# Generated by pdfforge-cli init for project %q.\n# pdf-forge: https://github.com/rendis/pdf-forge\n\n", name)
}
