// Code generated by pdfforge-cli init for project "pdftest".
// pdf-forge: https://github.com/rendis/pdf-forge

package injectors

import (
	"context"
	"time"

	"github.com/rendis/pdf-forge/sdk"
)

// ExampleImageInjector demonstrates an IMAGE type injectable.
// IMAGE injectables return URLs that are resolved when rendering documents.
type ExampleImageInjector struct{}

func (i *ExampleImageInjector) Code() string { return "example_image" }

func (i *ExampleImageInjector) Resolve() (sdk.ResolveFunc, []string) {
	return func(ctx context.Context, injCtx *sdk.InjectorContext) (*sdk.InjectorResult, error) {
		return &sdk.InjectorResult{
			Value: sdk.ImageValue("https://picsum.photos/seed/example/400/300"),
		}, nil
	}, nil
}

func (i *ExampleImageInjector) IsCritical() bool                  { return false }
func (i *ExampleImageInjector) Timeout() time.Duration             { return 0 }
func (i *ExampleImageInjector) DataType() sdk.ValueType            { return sdk.ValueTypeImage }
func (i *ExampleImageInjector) DefaultValue() *sdk.InjectableValue {
	v := sdk.ImageValue("https://picsum.photos/400/300")
	return &v
}
func (i *ExampleImageInjector) Formats() *sdk.FormatConfig { return nil }
