// Code generated by pdfforge-cli init for project "test-scaffold".
// pdf-forge: https://github.com/rendis/pdf-forge

package injectors

import (
	"context"
	"time"

	"github.com/rendis/pdf-forge/sdk"
)

// ExampleInjector is a sample injector that returns a static string.
type ExampleInjector struct{}

func (i *ExampleInjector) Code() string { return "example_value" }

func (i *ExampleInjector) Resolve() (sdk.ResolveFunc, []string) {
	return func(ctx context.Context, injCtx *sdk.InjectorContext) (*sdk.InjectorResult, error) {
		v := sdk.StringValue("Hello from " + injCtx.ExternalID())
		return &sdk.InjectorResult{Value: v}, nil
	}, nil // no dependencies
}

func (i *ExampleInjector) IsCritical() bool               { return false }
func (i *ExampleInjector) Timeout() time.Duration          { return 0 }
func (i *ExampleInjector) DataType() sdk.ValueType         { return sdk.ValueTypeString }
func (i *ExampleInjector) DefaultValue() *sdk.InjectableValue { return nil }
func (i *ExampleInjector) Formats() *sdk.FormatConfig      { return nil }
