// Code generated by pdfforge-cli init for project "test-scaffold".
// pdf-forge: https://github.com/rendis/pdf-forge

package main

import (
	"log"

	"github.com/rendis/pdf-forge/sdk"
	"test-scaffold/extensions"
	"test-scaffold/extensions/injectors"
)

func main() {
	engine := sdk.New(
		sdk.WithConfigFile("config/app.yaml"),
		sdk.WithI18nFile("config/injectors.i18n.yaml"),
	)

	// Register custom injectors
	engine.RegisterInjector(&injectors.ExampleInjector{})

	// Register mapper (handles request parsing for render)
	engine.RegisterMapper(&extensions.ExampleMapper{})

	// Register init function (loads shared data before injectors)
	engine.SetInitFunc(extensions.ExampleInit())

	// Auto-apply pending database migrations (idempotent)
	if err := engine.RunMigrations(); err != nil {
		log.Fatal("migrations: ", err)
	}

	if err := engine.Run(); err != nil {
		log.Fatal(err)
	}
}
